#Expyriment 0.11.dev5 (Python 3.12.0), .xpe-file, coding: UTF-8
#date: Wed Oct 16 2024 16:17:01
#sha1: 4da637
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Linux', node='is154920', release='6.8.0-45-lowlatency', version='#45.1~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep  6 15:26:10 UTC', machine='x86_64')
Time,Type,Event,Value,Detail,Detail2
830,design,log,
#design: #exp: Experiment
#design: block_cnt,block_id,trial_cnt,trial_id
830,design,logged,
830,Experiment,started
7861,stderr,received,'Traceback (most recent call last):'
7861,stderr,received,'  File "/home/cp983411/00_git/ppe/experiments/kinematogram/kinematogram_v0.py", line 31, in <module>'
7861,stderr,received,'    k.reset(100, random.sample([0, 180]), p)'
7861,stderr,received,'                 ^^^^^^'
7861,stderr,received,"NameError: name 'random' is not defined. Did you forget to import 'random'?"
7861,Data,saved
