#Expyriment 0.11.dev5 (Python 3.12.0), .xpe-file, coding: UTF-8
#date: Wed Oct 16 2024 16:17:57
#sha1: 26d275
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Linux', node='is154920', release='6.8.0-45-lowlatency', version='#45.1~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep  6 15:26:10 UTC', machine='x86_64')
Time,Type,Event,Value,Detail,Detail2
661,design,log,
#design: #exp: Experiment
#design: block_cnt,block_id,trial_cnt,trial_id
661,design,logged,
661,Experiment,started
7687,stderr,received,'Traceback (most recent call last):'
7687,stderr,received,'  File "/home/cp983411/00_git/ppe/experiments/kinematogram/kinematogram_v0.py", line 31, in <module>'
7687,stderr,received,'    k.reset(100, sample(1, [0, 180]), p)'
7687,stderr,received,'                 ^^^^^^^^^^^^^^^^^^^'
7687,stderr,received,'  File "/home/cp983411/.pyenv/versions/3.12.0/lib/python3.12/random.py", line 413, in sample'
7687,stderr,received,'    raise TypeError("Population must be a sequence.  "'
7687,stderr,received,'TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).'
7687,Data,saved
