#Expyriment 0.11.dev5 (Python 3.12.0), .xpe-file, coding: UTF-8
#date: Wed Oct 16 2024 15:37:25
#sha1: b8a951
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Linux', node='is154920', release='6.8.0-45-lowlatency', version='#45.1~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep  6 15:26:10 UTC', machine='x86_64')
Time,Type,Event,Value,Detail,Detail2
394,stderr,received,'Traceback (most recent call last):'
394,stderr,received,'  File "/home/cp983411/00_git/ppe/experiments/kinematogram/kine.py", line 21, in <module>'
395,stderr,received,'    k = extras.kinematograms()'
395,stderr,received,'        ^^^^^^'
395,stderr,received,"NameError: name 'extras' is not defined"
